//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorServicesClient.ProxyDemo.ServiceProxies.CalculatorServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProxies.CalculatorServices.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Add", ReplyAction="http://tempuri.org/ICalculator/AddResponse")]
        int Add(int number1, int number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Subtract", ReplyAction="http://tempuri.org/ICalculator/SubtractResponse")]
        int Subtract(int number1, int number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Divide", ReplyAction="http://tempuri.org/ICalculator/DivideResponse")]
        int Divide(int number1, int number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Multiply", ReplyAction="http://tempuri.org/ICalculator/MultiplyResponse")]
        int Multiply(int number1, int number2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Mod", ReplyAction="http://tempuri.org/ICalculator/ModResponse")]
        int Mod(int number1, int number2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : CalculatorServicesClient.ProxyDemo.ServiceProxies.CalculatorServices.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<CalculatorServicesClient.ProxyDemo.ServiceProxies.CalculatorServices.ICalculator>, CalculatorServicesClient.ProxyDemo.ServiceProxies.CalculatorServices.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int number1, int number2) {
            return base.Channel.Add(number1, number2);
        }
        
        public int Subtract(int number1, int number2) {
            return base.Channel.Subtract(number1, number2);
        }
        
        public int Divide(int number1, int number2) {
            return base.Channel.Divide(number1, number2);
        }
        
        public int Multiply(int number1, int number2) {
            return base.Channel.Multiply(number1, number2);
        }
        
        public int Mod(int number1, int number2) {
            return base.Channel.Mod(number1, number2);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProxies.CalculatorServices.IAdvancedCalculator")]
    public interface IAdvancedCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedCalculator/Sign", ReplyAction="http://tempuri.org/IAdvancedCalculator/SignResponse")]
        int Sign(int number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdvancedCalculatorChannel : CalculatorServicesClient.ProxyDemo.ServiceProxies.CalculatorServices.IAdvancedCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdvancedCalculatorClient : System.ServiceModel.ClientBase<CalculatorServicesClient.ProxyDemo.ServiceProxies.CalculatorServices.IAdvancedCalculator>, CalculatorServicesClient.ProxyDemo.ServiceProxies.CalculatorServices.IAdvancedCalculator {
        
        public AdvancedCalculatorClient() {
        }
        
        public AdvancedCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdvancedCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvancedCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvancedCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Sign(int number) {
            return base.Channel.Sign(number);
        }
    }
}
